CREATE TABLE IF NOT EXISTS `accounts` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`f_name` VARCHAR(255) NOT NULL,
	`l_name` VARCHAR(255) NOT NULL,
	`email` VARCHAR(255) NOT NULL,
	`pwd` VARCHAR(255) NOT NULL,
	`role` VARCHAR(20) NOT NULL DEFAULT 'user',
	`phone` VARCHAR(255),
	`dob` DATE,
	`zodiac` VARCHAR(255),
	`coin` INTEGER NOT NULL DEFAULT 50,
	`streak` INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `cards` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`pict` VARCHAR(255) NOT NULL,
	`name` VARCHAR(255) NOT NULL,
	`pred` TEXT(65535) NOT NULL,
	`adv` TEXT(65535) NOT NULL,
	`kind` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `diaries` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`acc_id` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `saves` (
	`card_id` INT UNSIGNED NOT NULL,
	`diary_id` INT UNSIGNED NOT NULL,
	`date` DATE NOT NULL,
	PRIMARY KEY(`card_id`, `diary_id`, `date`)
);


ALTER TABLE `diaries`
ADD FOREIGN KEY(`acc_id`) REFERENCES `accounts`(`id`)
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `saves`
ADD FOREIGN KEY(`card_id`) REFERENCES `cards`(`id`)
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE `saves`
ADD FOREIGN KEY(`diary_id`) REFERENCES `diaries`(`id`)
ON UPDATE CASCADE ON DELETE CASCADE;