CREATE TABLE IF NOT EXISTS `accounts` (
	`id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`f_name` VARCHAR(255) NOT NULL,
	`email` VARCHAR(255) NOT NULL,
	`pwd` VARCHAR(255) NOT NULL,
	`phone` VARCHAR(255),
	`dob` DATE,
	`zodiac` VARCHAR(255),
	`coin` INTEGER NOT NULL,
	`streak` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `cards` (
	`id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`pict` VARCHAR(255) NOT NULL,
	`name` VARCHAR(255) NOT NULL,
	`pred` TEXT(65535) NOT NULL,
	`adv` TEXT(65535) NOT NULL,
	`kind` VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `diaries` (
	`id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`acc_id` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `saves` (
	`card_id` INTEGER NOT NULL,
	`diary_id` INTEGER NOT NULL,
	`date` DATE NOT NULL,
	PRIMARY KEY(`card_id`, `diary_id`, `date`)
);


ALTER TABLE `diaries`
ADD FOREIGN KEY(`acc_id`) REFERENCES `accounts`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `saves`
ADD FOREIGN KEY(`card_id`) REFERENCES `cards`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `saves`
ADD FOREIGN KEY(`diary_id`) REFERENCES `diaries`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;